name: Build, lint and test with coverage
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Allow read access to pull request. Needed for the `only-new-issues` option of the golangci-lint action.
  pull-requests: read

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
          # Show only new issues if it's a pull request.
          # only-new-issues: true

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
          check-latest: true
      - name: Build
        run: make build
      - name: Test and show coverage
        run: make coverage-report-ci
